# -*- coding: utf-8 -*-
"""Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKzFvuidghxuoXxv78P2lb7HdAPzebZa
"""

print("Hello, World!")

x = 5
y = "John"
print(x)
print(y)

x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3)  # z will be 3.0
print(x,y,z)

x = 5
y = "John"
print(type(x))
print(type(y))

x = "John"
# is the same as
x = 'John'
# x=2
print(x)

a = 4
A = "Sally"
#A will not overwrite a

myvar = "John"
my_var = "John"
_my_var = "John"
myVar = "John"
MYVAR = "John"
myvar2 = "John"

x, y, z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)

x = y = z = "Orange"
print(x)
print(y)
print(z)

fruits = ["apple", "banana", "cherry"]
x, y, z = fruits
print(x)
print(y)
print(fruits)

thistuple = ("apple", "banana", "cherry", "apple", "cherry")
print(thistuple)
thistuple = ("apple", "banana", "cherry", "apple", "cherry", 3, 5, 6, 'grapes')
print(thistuple)

thisset = {"banana", "apple", "cherry", False, 1, 2}

print(thisset)

my_tuple = ("apple", "banana", "cherry")
print("First fruit:", my_tuple[0])
print("Number of fruits:", len(my_tuple))
for fruit in my_tuple:
    print("Fruit:", fruit)

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

my_list = [10, 20, 30, 40]

print("Second element:", my_list[1])
my_list.append(50)
print("Updated list:", my_list)
my_list.remove(30)
print("After removal:", my_list)
for num in my_list:
    print("Number:", num)

my_list = [10, 20, 30, 40]
my_list.insert(2, 25)

print("Updated list:", my_list)

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

my_dict = {
    "name": "Alice",
    "age": 25,
    "city": "New York"
}
print("Name:", my_dict["name"])
my_dict["email"] = "alice@example.com"
my_dict["age"] = 26
for key, value in my_dict.items():
    print(key, ":", value)



x = "Python "
y = "is "
z = "awesome"
print(x + y + z)

x = 5
y = "John"
print(x, y)



import sys

print(sys.version)

if 5 > 2:
  print("Five is greater than two!")

if 5 > 2:
 print("Five is greater than two!")
 if 5 > 1:
        print("Five is greater than two!")

a = 33
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

i = 1
while i < 6:
  print(i)
  i += 1

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

for x in range(7):
  print(x)
else:
  print("Finally finished!")

x = "awesome"

def myfunc():
  print("Python is " + x)

myfunc()

x = "awesome"

def myfunc():
  x = "fantastic"
  print("Python is " + x)

myfunc()

print("Python is " + x)

